### ISSUE TITLE
TODO OVERVIEW

### ISSUE THREAD

**Issue by lulebe** [lulebe/jscrusades#1]
- [x] player class
- [x] unit class
- [x] unit type list
- [x] units to player
- [x] Allow above to load from save
- [x] unit rendering
- [x] Change UI to 2 columns
- [x] turn logic
- [x] Turn UI

**Comment by lulebe** [comment]
NEXT UP:

- [x] Basic conquering, healing, resupply functions
- [x] Movement and pathfinding algorithm
- [x] Render reachable fields for movement
- [x] Implement moves & move animation

**Comment by lulebe** [comment]
------

- [x] Create bearable UI for sidebar, game over and index page
- [x] Savegame management
- [x] Allow reloading game from "gameSave" mid-round (for online mp sync)
- [x] create online-mp action packets to send live to opponent
- [x] create server thingy
- [x] AI
- [x] Sounds & music?
- [x] Battle screen

**Comment by lulebe** [comment]
- [x] some original Maps start with units, needs to be implemented
- [x] import remaining maps
- [ ] basic map editor
- [ ] frontend to play custom maps
- [ ] 5 letter fields in map strings
- [x] map compression
- [ ] map sharing via url
